# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpcapi_pb2 as rpcapi__pb2


class RpcApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Execute = channel.unary_unary(
        '/cfgrpcapi.RpcApi/Execute',
        request_serializer=rpcapi__pb2.ExecuteRequest.SerializeToString,
        response_deserializer=rpcapi__pb2.ExecuteReply.FromString,
        )


class RpcApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Execute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RpcApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Execute': grpc.unary_unary_rpc_method_handler(
          servicer.Execute,
          request_deserializer=rpcapi__pb2.ExecuteRequest.FromString,
          response_serializer=rpcapi__pb2.ExecuteReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cfgrpcapi.RpcApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
